org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

## Environment Properties
minecraft_version=1.20.1
minecraft_version_range=[1.20.1]
forge_version=47.4.23
forge_version_range=[47.4.23,48)
loader_version_range=[47,48)

## Mod Properties
mod_id=kilagraph
mod_name=KilaGraph
mod_license=MIT-LICENSE
mod_version=20.1.0.12
mod_group_id=com.lowdragmc.kilagraph
mod_authors=KilaBash
mod_url=https://github.com/supermerlin204/kilagraph-1.20.1-forge
mod_description=KilaGraph is a mod that adds the node graph features to the game.
archives_name=kilagraph-forge-1.20.1

## LDLib2 Properties
ldlib2_version_range=[2.2.37,)
